# .travis.yml

language: objective-c
osx_image: xcode8.3
before_install:
  - gem i slather --no-ri --no-rdoc
script:
  - xcodebuild -scheme SwiftAlgorithmsAndDataStructuresDojo -project SwiftAlgorithmsAndDataStructuresDojo.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' build test
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f Slather/cobertura.xml -X coveragepy -X gcov -X xcode
